### ISSUE TITLE
arDesktop not opening/loading on system tray.

### ISSUE THREAD

**Issue by quaam** [alexanderrichtertd/plex#25]
I can't seem to get desktop.bat to work. 
arDesktop is not opening or loading on system tray. Is that currently working?

**Comment by alexanderrichtertd** [comment]
Yes, it working.
Probably a problem with either you Python or PySide version especially if the DCCs are working.
Check your log (data/user/USERNAME/USERNAME.log) what it says last.
Could be something like "Can't import PySide" which means your PySide is not set properly. 

Best, Alex

**Comment by quaam** [comment]
Hey thanks for the reply, I just checked the log and don't see an error. 

I've attached the log.
[monap.log](https://github.com/alexanderrichtertd/plex/files/2298661/monap.log)

**Comment by quaam** [comment]
I did a reinstall and was able to get it to work now. must have been something in the configuration that was conflicting.

**Comment by alexanderrichtertd** [comment]
Best IT Solve :+1:
