### ISSUE TITLE
arSaveAs/asset

### ISSUE THREAD

**Issue by JaximusQ** [alexanderrichtertd/plex#53]
Hi,
I'm in the arSaveAs windows and when I switch to <asset> I get this error message :
FAILED adding tasks items: data/project/$project/rules.yml : TASK
And then no tasks are shown in the task box.

I went to "<project>/00_pipeline/data/project/<project>/" and in this folder I have no rules.yml file. 
I check inside the project.yml and all the rules and task information are inside it.

Might it be something wrong with my project setup ? Is it a common issue ?

**Comment by alexanderrichtertd** [comment]
Hey my friends,

good point. I merged _rules.yml_ into _project.yml_ since there was not much of a point to have it outside. Updated the print in the newest version.

Seems arSave and arLoad have some issues. Need to update them in the next days including the template project.

Keep you posted!

**Comment by alexanderrichtertd** [comment]
Updated arLoad and arSave.

Also added some tools from the menu to the shelf:
rendersettings, open current folder and open project folder.

![image](https://user-images.githubusercontent.com/9514022/77828952-f7e29280-711e-11ea-956e-fa02ff3ef89d.png)

Thank you for the feedback!
